Different token for original and alias
As we upload two projects to PyPI (kivy-garden.mapview & mapview)
we need two different tokens, hence two different jobs.
Testing it we got a:
```
HTTPError: 400 Client Error: File already exists.
See https://pypi.org/help/#file-name-reuse for url: https://upload.pypi.org/legacy/
```
For both jobs, which means the credentials are working.
https://github.com/kivy-garden/mapview/runs/600987339